provider "aws" {
  region = "us-west-2"  # Set your AWS region
}

# ECS Cluster
resource "aws_ecs_cluster" "my_cluster" {
  name = "my-ecs-cluster"
}

# Register Task Definitions (using the HCL files generated by the script)
module "task_definitions" {
  source = "./terraform_task_definitions"  # Directory where HCL files are generated
}

# Create or update ECS services for each task definition
resource "aws_ecs_service" "my_service" {
  count               = length(module.task_definitions.task_definition_arns)
  name                = "my-ecs-service-${count.index}"
  cluster             = aws_ecs_cluster.my_cluster.id
  task_definition     = module.task_definitions.task_definition_arns[count.index]
  desired_count       = 1
  launch_type         = "FARGATE"
  
  network_configuration {
    subnets          = ["subnet-12345678", "subnet-87654321"]
    assign_public_ip = true
  }
  
  load_balancer {
    target_group_arn = aws_lb_target_group.my_target_group.arn
    container_name   = "my-container"
    container_port   = 80
  }
}
